In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("taxi_trip_pricing.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       950 non-null    float64
 1   Time_of_Day            950 non-null    object
 2   Day_of_Week            950 non-null    object
 3   Passenger_Count        950 non-null    float64
 4   Traffic_Conditions     950 non-null    object
 5   Weather                950 non-null    object
 6   Base_Fare              950 non-null    float64
 7   Per_Km_Rate            950 non-null    float64
 8   Per_Minute_Rate        950 non-null    float64
 9   Trip_Duration_Minutes  950 non-null    float64
 10  Trip_Price             951 non-null    float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB

In [4]:
df.columns

Index(['Trip_Distance_km', 'Time_of_Day', 'Day_of_Week', 'Passenger_Count',
       'Traffic_Conditions', 'Weather', 'Base_Fare', 'Per_Km_Rate',
       'Per_Minute_Rate', 'Trip_Duration_Minutes', 'Trip_Price'],
      dtype='object')

In [5]:
df.shape

(1000, 11)

In [6]:
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [7]:
df = df.dropna()

In [8]:
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
5,8.64,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028
12,41.79,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.1328
14,9.91,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.9914

In [9]:
df.shape

(562, 11)

In [10]:
df.columns = ['seyahat_mesafesi','gunun_saati','haftanin_gunu','yolcu_sayisi','trafik_kosullari','hava_durumu','temel_ucret','km_basina_ucret','dk_basina_ucret','seyahat_suresi','seyahat_ucreti']
df.head()

,seyahat_mesafesi,gunun_saati,haftanin_gunu,yolcu_sayisi,trafik_kosullari,hava_durumu,temel_ucret,km_basina_ucret,dk_basina_ucret,seyahat_suresi,seyahat_ucreti
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
5,8.64,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028
12,41.79,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.1328
14,9.91,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.9914

In [11]:
df.gunun_saati

0        Morning
2        Evening
5      Afternoon
12         Night
14       Evening
         ...
990      Evening
992    Afternoon
994      Evening
995    Afternoon
998      Morning
Name: gunun_saati, Length: 562, dtype: object

In [12]:
gunun_saati = df.gunun_saati.unique()
print(gunun_saati)

['Morning' 'Evening' 'Afternoon' 'Night']

In [13]:
df['gunun_saati'] = df['gunun_saati'].replace({'Morning':0,'Evening':1,'Afternoon':2,'Night':3})
df.head(3)

C:\Users\kurt_\AppData\Local\Temp\ipykernel_1260\2649637558.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gunun_saati'] = df['gunun_saati'].replace({'Morning':0,'Evening':1,'Afternoon':2,'Night':3})

,seyahat_mesafesi,gunun_saati,haftanin_gunu,yolcu_sayisi,trafik_kosullari,hava_durumu,temel_ucret,km_basina_ucret,dk_basina_ucret,seyahat_suresi,seyahat_ucreti
0,19.35,0,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
2,36.87,1,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
5,8.64,2,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028

In [14]:
haftanin_gunu = df.haftanin_gunu.unique()
print(haftanin_gunu)

['Weekday' 'Weekend']

In [15]:
df['haftanin_gunu'] = df['haftanin_gunu'].replace({'Weekday':0,'Weekend':1})
df.head(3)

C:\Users\kurt_\AppData\Local\Temp\ipykernel_1260\2308356319.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['haftanin_gunu'] = df['haftanin_gunu'].replace({'Weekday':0,'Weekend':1})

,seyahat_mesafesi,gunun_saati,haftanin_gunu,yolcu_sayisi,trafik_kosullari,hava_durumu,temel_ucret,km_basina_ucret,dk_basina_ucret,seyahat_suresi,seyahat_ucreti
0,19.35,0,0,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
2,36.87,1,1,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
5,8.64,2,1,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028

In [16]:
hava_durumu = df.hava_durumu.unique()
print(hava_durumu)

['Clear' 'Rain' 'Snow']

In [17]:
df['hava_durumu'] = df['hava_durumu'].replace({'Clear':0,'Rain':1,'Snow':2})
df.head(3)

C:\Users\kurt_\AppData\Local\Temp\ipykernel_1260\2649238164.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['hava_durumu'] = df['hava_durumu'].replace({'Clear':0,'Rain':1,'Snow':2})

,seyahat_mesafesi,gunun_saati,haftanin_gunu,yolcu_sayisi,trafik_kosullari,hava_durumu,temel_ucret,km_basina_ucret,dk_basina_ucret,seyahat_suresi,seyahat_ucreti
0,19.35,0,0,3.0,Low,0,3.56,0.80,0.32,53.82,36.2624
2,36.87,1,1,1.0,High,0,2.70,1.21,0.15,37.27,52.9032
5,8.64,2,1,2.0,Medium,0,2.55,1.71,0.48,89.33,60.2028

In [18]:
trafik_kosullari = df.trafik_kosullari.unique()
print(trafik_kosullari)

['Low' 'High' 'Medium']

In [19]:
df['trafik_kosullari'] = df['trafik_kosullari'].replace({'Low':0,'High':1,'Medium':2})
df.head(3)

C:\Users\kurt_\AppData\Local\Temp\ipykernel_1260\716571307.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['trafik_kosullari'] = df['trafik_kosullari'].replace({'Low':0,'High':1,'Medium':2})

,seyahat_mesafesi,gunun_saati,haftanin_gunu,yolcu_sayisi,trafik_kosullari,hava_durumu,temel_ucret,km_basina_ucret,dk_basina_ucret,seyahat_suresi,seyahat_ucreti
0,19.35,0,0,3.0,0,0,3.56,0.80,0.32,53.82,36.2624
2,36.87,1,1,1.0,1,0,2.70,1.21,0.15,37.27,52.9032
5,8.64,2,1,2.0,2,0,2.55,1.71,0.48,89.33,60.2028

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 562 entries, 0 to 998
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   seyahat_mesafesi  562 non-null    float64
 1   gunun_saati       562 non-null    int64
 2   haftanin_gunu     562 non-null    int64
 3   yolcu_sayisi      562 non-null    float64
 4   trafik_kosullari  562 non-null    int64
 5   hava_durumu       562 non-null    int64
 6   temel_ucret       562 non-null    float64
 7   km_basina_ucret   562 non-null    float64
 8   dk_basina_ucret   562 non-null    float64
 9   seyahat_suresi    562 non-null    float64
 10  seyahat_ucreti    562 non-null    float64
dtypes: float64(7), int64(4)
memory usage: 52.7 KB

In [21]:
x = df.drop(['seyahat_ucreti'],axis = 1)
y = df['seyahat_ucreti']

In [36]:
print(x.shape)
print(y.shape)

(562, 10)
(562,)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.70,random_state = 22)

In [35]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(393, 10)
(169, 10)
(393,)
(169,)

In [33]:
from sklearn.linear_model import LinearRegression

In [37]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [40]:
df.head(3)

,seyahat_mesafesi,gunun_saati,haftanin_gunu,yolcu_sayisi,trafik_kosullari,hava_durumu,temel_ucret,km_basina_ucret,dk_basina_ucret,seyahat_suresi,seyahat_ucreti
0,19.35,0,0,3.0,0,0,3.56,0.80,0.32,53.82,36.2624
2,36.87,1,1,1.0,1,0,2.70,1.21,0.15,37.27,52.9032
5,8.64,2,1,2.0,2,0,2.55,1.71,0.48,89.33,60.2028

In [41]:
model.predict([[25,1,1,5,2,0,2,1.5,0.5,31.31]])

C:\Users\kurt_\anaconda3\envs\veri-analizi\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([67.07765846])

In [43]:
import numpy as np
np.array(y_test.iloc[20])

array(44.844)

In [47]:
print(x_test.index)

Index([157, 765, 572, 622, 529, 521, 594,  59, 241, 365,
       ...
       337, 564, 347, 120, 293, 769,  48, 884, 259, 281],
      dtype='int64', length=169)

In [49]:
print(x_test.loc[157])

seyahat_mesafesi    38.32
gunun_saati          1.00
haftanin_gunu        0.00
yolcu_sayisi         1.00
trafik_kosullari     2.00
hava_durumu          0.00
temel_ucret          4.58
km_basina_ucret      0.98
dk_basina_ucret      0.37
seyahat_suresi      28.41
Name: 157, dtype: float64

In [52]:
model.predict([[38.32,1,0,1,2,0,4.58,0.98,0.37,28.41]])

C:\Users\kurt_\anaconda3\envs\veri-analizi\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([66.80307995])

In [53]:
print(y_test.loc[157])

52.6453

In [54]:
model.score(x_test,y_test)

0.8596416290683111